### ISSUE TITLE
[ Feature Request ] Other View

### ISSUE THREAD

**Issue by soehlert** [prodicus/tnote#1]
Something like tags or some sort of list view. Something so you don't have to scroll through each one individually like that. I think that would make me ready to really give it a try. Thanks!

**Comment by prodicus** [comment]
Hey @soehlert 

That is one of the first things that I have in mind for adding. Thanks for your time by the way :smile:

**Comment by prodicus** [comment]
#3

**Comment by prodicus** [comment]
#3 closes this
