### ISSUE TITLE
"puts" syntax error line 140

### ISSUE THREAD

**Issue by jonbash** [prodicus/tnote#15]
I'm on Mac OS X, and after following all instructions (except putting the alias in /usr/local/bin instead) I'm getting the following error:

``` python
  File "/usr/local/bin/tnote", line 140
    puts(colored.green("="*(len(title_string)+33)))  
       ^  
SyntaxError: invalid syntax
```

Rendering it unusable. Not sure why...?

**Comment by prodicus** [comment]
Hey @jonbash 

Looking at the traceback, `tnote` is inside your `bin` directory. 
How are you calling the program?

**Comment by jonbash** [comment]
Thank you for the time and assistance.

Just tried reinstalling using pip3 instead, but didn't seem to make a difference.

All requirements are installed. As seen below when running `pip3 install -r requirements.txt`.

```
Requirement already satisfied (use --upgrade to upgrade): args==0.1.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): clint==0.5.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pysqlcipher3==1.0.2 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 5))
```

I'm calling the program via `$ tnote`. 

It looks like a great program! Wish I knew more python so I could dig into the code myself, haha.

**Comment by prodicus** [comment]
Hey @jonbash. Not a problem at all. The app was made backwards compatible with `python2`, so it shouldn't be a versioning problem.

Could you call `tnote` like this and post the traceback.

```bash
$ chmod +x tnote
$ ./tnote
```

**Comment by jonbash** [comment]
Sure thing:

```
$ ./tnote
  File "./tnote", line 140
    puts(colored.green("="*(len(title_string)+33)))
       ^
SyntaxError: invalid syntax
```

**Comment by prodicus** [comment]
Hey @jonbash .

It seems there is a problem with the `ciint` interface which gives the colors to tnote. Looks like the API changes broke the app.

Too bad.

**Comment by EoleDev** [comment]
Hey,

I am really disappointed by your code and the time you need to correct the error which was reported here.
The solution is just to add a parenthesis at the end of the previous line... yes it miss one here...
but it brings some other error.

**Comment by prodicus** [comment]
Hey @EoleDev , 

`tnote` stands open sourced at this point of time so if you see any error in the code or any other shortcomings in it then feel free to make a PR for it. 

As for the maintenance of the project, I am finding it hard to find time to fix the issues here. 

Hope I answered your query.

Cheer!

**Comment by prodicus** [comment]
@jonbash Hope it works out for you now. If not, will reopen the issue
